#!/usr/bin/env bash
# install nginx on the server
# update apt and install nginx
sudo apt-get update
sudo apt-get -y install nginx
# replace the default index.html with hello world
echo "Hello World!" | sudo tee /var/www/html/index.html
# restart to apply the changes
sudo service nginx restart
