#!/usr/bin/env bash
# install nginx on the server
sudo apt-get update
sudo apt-get -y install nginx
# sudo ufw allow 'Nginx HTTP'
# sudo mkdir -p /var/www/helloWorld.com/html
# sudo chown -R "$USER":"$USER" /var/www/helloWorld.com/html
# sudo chmod -R 755 /var/www
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
# sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/helloWorld.com
# sudo sed -i 's/root \/var\/www\/html/root \/var\/www\/helloWorld.com\/html/g' /etc/nginx/sites-available/helloWorld.com
# sudo sed -i 's/default_server//g' /etc/nginx/sites-available/helloWorld.com
# sudo ln -s /etc/nginx/sites-available/helloWorld.com /etc/nginx/sites-enabled/
sudo service nginx restart
