#!/usr/bin/env bash
# install nginx on the server
# update apt and install nginx
sudo apt-get update
sudo apt-get -y install nginx
# replace the default index.html with hello world
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
# redirect page redirect_me to youtube
FILENGINX="/etc/nginx/sites-available/default"
STR="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/dQw4w9WgXcQ; \n\t}\n"
sed -i "37i\ $REDIRECT" "$FILENGINX"
# restart to apply the changes
sudo service nginx restart
