#!/usr/bin/env bash
# install nginx on the server
# update apt and install nginx
sudo apt-get update
sudo apt-get -y install nginx
# replace the default index.html with hello world
echo "Hello World!" | sudo tee /var/www/html/index.html
# redirect page redirect_me to youtube
FILENGINX="/etc/nginx/sites-available/default"
STR="location /redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}"
sudo sed -i "/server_name _;/a $STR" "$FILENGINX"
# restart to apply the changes
sudo service nginx restart
