#!/usr/bin/env bash
# install nginx on the server
# update apt and install nginx
sudo apt-get update
sudo apt-get -y install nginx
# replace the default index.html with hello world
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
# redirect page redirect_me to youtube
FILENGINX="/etc/nginx/sites-available/default"
SERVER="server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        error_page 404 /404.html;
        location /redirect_me {
            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
    }"
echo "$SERVER" | sudo tee "$FILENGINX"
# error 404
echo "Ceci n'est pas une page" | sudo tee /404.html
# restart to apply the changes
sudo service nginx restart
