#!/usr/bin/env bash
# Bash script that configures a server listening on port 80 of all the server’s active IPv4 IPs
sudo sed  -i 's/8080/80/' /etc/nginx/sites-enabled/default
sudo service nginx restart
kill $(cat /var/run/nginx.pid)