#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes

i=0
j=0
while [ $i -lt 13 ]; do
	j=0
	echo "Hour: $i"
	while [ $j -lt 59 ]; do
		((j++))
		echo "$j"
	done
	((i++))
done
