#!/usr/bin/env bash
# Bash script that Fix the container so that Nginx is running as the nginx user
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i '1iuser nginx nginx' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo service nginx restart
